jwt_hmac_secret: 'my$ecretK3y'

system_email:
  domain: 'gmail.com'
  user_name: 'learning.system.mailbot@gmail.com'
  password: 'wqnhpfwgsjctjvbb'

reset_password_page: 'http://localhost:5173/reset_password'


Admin:
  routes: ['/admin_interface', '/admin_interface/account_management', '/admin_interface/branch_school_management']
  root: '/admin_interface'

Student:
  routes: ['/', '/booking', '/booking_search', '/assignment_review', '/learning_record']
  root: '/'

ClassAdviser:
  routes: ['/class_adviser_interface', '/class_adviser_interface/administration_staff_management', '/class_adviser_interface/teacher_management', '/class_adviser_interface/teacher_schedule']
  root: '/class_adviser_interface'